[tools]
go = "latest"
dart = "latest"
hugo-extended = "0.165.0"
wrangler = "4.129.0"
node = "24.20.0"

[tools."github:sass/dart-sass"]
version = "1.104.0"
extract_all = true
executable = "dart-sass/sass"
