[tools]
go = "latest"
dart = "latest"
hugo-extended = "0.161.1"
wrangler = "4.92.0"
node = "24.16.0"

[tools."github:sass/dart-sass"]
version = "1.99.0"
extract_all = true
executable = "dart-sass/sass"
