[tools]
go = "latest"
dart = "latest"
hugo-extended = "0.166.0"
wrangler = "4.131.1"
node = "24.21.0"

[tools."github:sass/dart-sass"]
version = "1.104.0"
extract_all = true
executable = "dart-sass/sass"
